# ??????
spring:
  application:
    name: inkoj-backend-user-service
  # ?? dev ??
  profiles:
    active: dev
  # ?? swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session ??
  session:
    store-type: redis
    # 30 ???
    timeout: 2592000
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.63.13.13:3306/inkoj
    username: root
    password: Hit2021112678?
  # Redis ??
  redis:
    database: 1
    host: 116.63.13.13
    port: 6379
    timeout: 5000
    password: Hit2021112678?
  servlet:
    multipart:
      # ????
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 116.63.13.13:8848
server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/user
    # cookie 30 ???
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?
# ??????
codesandbox:
  type: remote
knife4j:
  enable: true
